name: btrfs-progs
version: '0.3.0'
base: core20
summary: btrfs tools
description: |
  A snap for btrfs tools  

confinement: devmode
grade: stable

architectures:
   - build-on: armhf
     run-on: armhf

apps:
  btrfs:
    command: bin/btrfs
    plugs:
      - removable-media
      - mount-observe
parts:
  btrfs-tools:
    plugin: nil
    stage-packages:
      - btrfs-progs
