name: btrfs-progs
version: '0.6.0'
base: core20
summary: btrfs tools
description: |
  A snap for btrfs tools  

confinement: strict
grade: stable

apps:
  btrfs:
    command: bin/btrfs
    plugs:
      - removable-media
      - mount-observe
parts:
  btrfs-tools:
    plugin: nil
    stage-packages:
      - btrfs-progs
